module.exports.lmNavFooterData = {
  navigation: {
    productsData: [
      {
        id: "vvs",
        name: "VVS",
        subCategories: [
          {
            id: "13",
            name: "Rør og fittings",
            subCategories: [
              {
                id: "122559",
                name: "Gevind fittings",
                subCategories: [],
                url: "/api/content/1088/category/122559",
              },
              {
                id: "122560",
                name: "Svejsefittings",
                subCategories: [],
                url: "/api/content/1088/category/122560",
              },
              {
                id: "101617",
                name: "Pex-systemer",
                subCategories: [],
                url: "/api/content/1088/category/101617",
              },
              {
                id: "101618",
                name: "Alu-pex systemer",
                subCategories: [],
                url: "/api/content/1088/category/101618",
              },
              {
                id: "122562",
                name: "Flanger",
                subCategories: [],
                url: "/api/content/1088/category/122562",
              },
              {
                id: "122563",
                name: "Levnedsmiddel fittings",
                subCategories: [],
                url: "/api/content/1088/category/122563",
              },
              {
                id: "101615",
                name: "Pressrør og fittings",
                subCategories: [],
                url: "/api/content/1088/category/101615",
              },
              {
                id: "101621",
                name: "Kloak produkter",
                subCategories: [],
                url: "/api/content/1088/category/101621",
              },
              {
                id: "108154",
                name: "Kompressions fittings",
                subCategories: [],
                url: "/api/content/1088/category/108154",
              },
              {
                id: "122569",
                name: "Kobberrør og fittings",
                subCategories: [],
                url: "/api/content/1088/category/122569",
              },
              {
                id: "101851",
                name: "Rørophæng og rørkoblinger",
                subCategories: [],
                url: "/api/content/1088/category/101851",
              },
              {
                id: "101619",
                name: "Vandforsynings produkter",
                subCategories: [],
                url: "/api/content/1088/category/101619",
              },
              {
                id: "102492",
                name: "Kunststof rør og fittings",
                subCategories: [],
                url: "/api/content/1088/category/102492",
              },
              {
                id: "101620",
                name: "Afløbs produkter",
                subCategories: [],
                url: "/api/content/1088/category/101620",
              },
              {
                id: "122575",
                name: "Pakmateriale",
                subCategories: [],
                url: "/api/content/1088/category/122575",
              },
              {
                id: "102490",
                name: "Bøsninger, rosetter, murtætninger og anboringsbøjler",
                subCategories: [],
                url: "/api/content/1088/category/102490",
              },
              {
                id: "101622",
                name: "Tag og facade",
                subCategories: [],
                url: "/api/content/1088/category/101622",
              },
            ],
            url: "/api/content/1088/category/13",
          },
          {
            id: "14",
            name: "Varme",
            subCategories: [
              {
                id: "106629",
                name: "Måleinstrumenter",
                subCategories: [],
                url: "/api/content/1088/category/106629",
              },
              {
                id: "101625",
                name: "Kedler og skorstene",
                subCategories: [],
                url: "/api/content/1088/category/101625",
              },
              {
                id: "101626",
                name: "Oliefyr og tilbehør",
                subCategories: [],
                url: "/api/content/1088/category/101626",
              },
              {
                id: "106606",
                name: "Varmtvandsbeholdere",
                subCategories: [],
                url: "/api/content/1088/category/106606",
              },
              {
                id: "108984",
                name: "El-varme",
                subCategories: [],
                url: "/api/content/1088/category/108984",
              },
              {
                id: "101633",
                name: "Pumper",
                subCategories: [],
                url: "/api/content/1088/category/101633",
              },
              {
                id: "101629",
                name: "Vekslere",
                subCategories: [],
                url: "/api/content/1088/category/101629",
              },
              {
                id: "101634",
                name: "Armaturer",
                subCategories: [],
                url: "/api/content/1088/category/101634",
              },
              {
                id: "101631",
                name: "Gulvvarme",
                subCategories: [],
                url: "/api/content/1088/category/101631",
              },
              {
                id: "101630",
                name: "Radiator & Ventiler",
                subCategories: [],
                url: "/api/content/1088/category/101630",
              },
              {
                id: "101628",
                name: "Luftopvarmning",
                subCategories: [],
                url: "/api/content/1088/category/101628",
              },
              {
                id: "101635",
                name: "Varmeautomatik",
                subCategories: [],
                url: "/api/content/1088/category/101635",
              },
              {
                id: "106568",
                name: "Brandmateriel",
                subCategories: [],
                url: "/api/content/1088/category/106568",
              },
              {
                id: "101636",
                name: "Isoleringmateriel",
                subCategories: [],
                url: "/api/content/1088/category/101636",
              },
              {
                id: "127579",
                name: "Gasvarme",
                subCategories: [],
                url: "/api/content/1088/category/127579",
              },
            ],
            url: "/api/content/1088/category/14",
          },
          {
            id: "15",
            name: "Bad og sanitet",
            subCategories: [
              {
                id: "101638",
                name: "Toiletter, sæder, bideter og reservedele",
                subCategories: [],
                url: "/api/content/1088/category/101638",
              },
              {
                id: "102936",
                name: "Installationssystemer",
                subCategories: [],
                url: "/api/content/1088/category/102936",
              },
              {
                id: "101639",
                name: "Håndvaske",
                subCategories: [],
                url: "/api/content/1088/category/101639",
              },
              {
                id: "101642",
                name: "Stålvaske",
                subCategories: [],
                url: "/api/content/1088/category/101642",
              },
              {
                id: "101643",
                name: "Blandingsbatterier og armaturer",
                subCategories: [],
                url: "/api/content/1088/category/101643",
              },
              {
                id: "101644",
                name: "Brus & Monteringstilbehør",
                subCategories: [],
                url: "/api/content/1088/category/101644",
              },
              {
                id: "101648",
                name: "Baderumsmøbler",
                subCategories: [],
                url: "/api/content/1088/category/101648",
              },
              {
                id: "101881",
                name: "Håndklæderadiator / Tilbehør",
                subCategories: [],
                url: "/api/content/1088/category/101881",
              },
              {
                id: "101645",
                name: "Reservedele & tilbehør til armaturer",
                subCategories: [],
                url: "/api/content/1088/category/101645",
              },
              {
                id: "101641",
                name: "Bruseafskærmninger, brusekabiner og tilbehør",
                subCategories: [],
                url: "/api/content/1088/category/101641",
              },
              {
                id: "101640",
                name: "Badekar",
                subCategories: [],
                url: "/api/content/1088/category/101640",
              },
              {
                id: "101647",
                name: "Badeværelses  tilbehør",
                subCategories: [],
                url: "/api/content/1088/category/101647",
              },
              {
                id: "112343",
                name: "RE-HAB & Care",
                subCategories: [],
                url: "/api/content/1088/category/112343",
              },
              {
                id: "101646",
                name: "Ventiler / Kuglehaner / Haneforlængere / Nødbrusere",
                subCategories: [],
                url: "/api/content/1088/category/101646",
              },
              {
                id: "125125",
                name: "Smarthome",
                subCategories: [],
                url: "/api/content/1088/category/125125",
              },
              {
                id: "124100",
                name: "Minikøkkener",
                subCategories: [],
                url: "/api/content/1088/category/124100",
              },
            ],
            url: "/api/content/1088/category/15",
          },
          {
            id: "24",
            name: "Energi og klima",
            subCategories: [
              {
                id: "127769",
                name: "Solceller",
                subCategories: [],
                url: "/api/content/1088/category/127769",
              },
              {
                id: "112806",
                name: "Diverse solcelle",
                subCategories: [],
                url: "/api/content/1088/category/112806",
              },
              {
                id: "115987",
                name: "Solvarme",
                subCategories: [],
                url: "/api/content/1088/category/115987",
              },
              {
                id: "101627",
                name: "Varmepumper",
                subCategories: [],
                url: "/api/content/1088/category/101627",
              },
              {
                id: "101632",
                name: "Ventilation",
                subCategories: [],
                url: "/api/content/1088/category/101632",
              },
            ],
            url: "/api/content/1088/category/24",
          },
        ],
        url: "/api/content/1088/category/vvs",
      },
      {
        id: "el",
        name: "EL",
        subCategories: [
          {
            id: "5",
            name: "El-teknik",
            subCategories: [
              {
                id: "103974",
                name: "Tavler og kasser",
                subCategories: [],
                url: "/api/content/1088/category/103974",
              },
              {
                id: "103588",
                name: "Komponenter til tavler og kasser",
                subCategories: [],
                url: "/api/content/1088/category/103588",
              },
              {
                id: "100097",
                name: "Føringsveje & kanalskinner",
                subCategories: [],
                url: "/api/content/1088/category/100097",
              },
              {
                id: "100016",
                name: "Forgreningsmateriel",
                subCategories: [],
                url: "/api/content/1088/category/100016",
              },
              {
                id: "103438",
                name: "Afbrydermateriel",
                subCategories: [],
                url: "/api/content/1088/category/103438",
              },
              {
                id: "100054",
                name: "Afbrydere, stik og stikpropper",
                subCategories: [],
                url: "/api/content/1088/category/100054",
              },
              {
                id: "103192",
                name: "El-apparater",
                subCategories: [],
                url: "/api/content/1088/category/103192",
              },
              {
                id: "100026",
                name: "Jording og Transientbeskyttelse",
                subCategories: [],
                url: "/api/content/1088/category/100026",
              },
              {
                id: "100120",
                name: "Antennemateriel",
                subCategories: [],
                url: "/api/content/1088/category/100120",
              },
              {
                id: "100031",
                name: "Intelligente bygningsinstallationer",
                subCategories: [],
                url: "/api/content/1088/category/100031",
              },
              {
                id: "100262",
                name: "PLC-styring, HMI og Industri PC",
                subCategories: [],
                url: "/api/content/1088/category/100262",
              },
              {
                id: "113042",
                name: "Industrielle netværk",
                subCategories: [],
                url: "/api/content/1088/category/113042",
              },
              {
                id: "100242",
                name: "Sensorik",
                subCategories: [],
                url: "/api/content/1088/category/100242",
              },
              {
                id: "100234",
                name: "Trykknapper og signalenheder",
                subCategories: [],
                url: "/api/content/1088/category/100234",
              },
              {
                id: "100239",
                name: "Maskinsikkerhed",
                subCategories: [],
                url: "/api/content/1088/category/100239",
              },
              {
                id: "100245",
                name: "Motorstyring",
                subCategories: [],
                url: "/api/content/1088/category/100245",
              },
              {
                id: "104243",
                name: "Bevægelsesmelder og skumringsrelæ",
                subCategories: [],
                url: "/api/content/1088/category/104243",
              },
            ],
            url: "/api/content/1088/category/5",
          },
          {
            id: "7",
            name: "Tele, data og sikkerhed",
            subCategories: [
              {
                id: "124719",
                name: "Digital skiltning",
                subCategories: [],
                url: "/api/content/1088/category/124719",
              },
              {
                id: "100204",
                name: "Telefoni",
                subCategories: [],
                url: "/api/content/1088/category/100204",
              },
              {
                id: "100214",
                name: "Udtag & bokse",
                subCategories: [],
                url: "/api/content/1088/category/100214",
              },
              {
                id: "100216",
                name: "Dataelektronik",
                subCategories: [],
                url: "/api/content/1088/category/100216",
              },
              {
                id: "100217",
                name: "UPS-anlæg",
                subCategories: [],
                url: "/api/content/1088/category/100217",
              },
              {
                id: "100223",
                name: "Sikkerhed",
                subCategories: [],
                url: "/api/content/1088/category/100223",
              },
              {
                id: "101786",
                name: "Testere og værktøj",
                subCategories: [],
                url: "/api/content/1088/category/101786",
              },
              {
                id: "104725",
                name: "Gulv & vægrack",
                subCategories: [],
                url: "/api/content/1088/category/104725",
              },
              {
                id: "105150",
                name: "Fiber kabling",
                subCategories: [],
                url: "/api/content/1088/category/105150",
              },
              {
                id: "106540",
                name: "Patch- tilslutnings, AV kabler, adapter & konverter",
                subCategories: [],
                url: "/api/content/1088/category/106540",
              },
              {
                id: "100086",
                name: "Kabling kobber",
                subCategories: [],
                url: "/api/content/1088/category/100086",
              },
              {
                id: "100229",
                name: "Talevarsling(PA) og lydsystemer",
                subCategories: [],
                url: "/api/content/1088/category/100229",
              },
            ],
            url: "/api/content/1088/category/7",
          },
          {
            id: "23",
            name: "Kabler, ledninger, afdækning og brandsikring",
            subCategories: [
              {
                id: "126225",
                name: "Installationskabler",
                subCategories: [],
                url: "/api/content/1088/category/126225",
              },
              {
                id: "126408",
                name: "Industrikabler",
                subCategories: [],
                url: "/api/content/1088/category/126408",
              },
              {
                id: "126447",
                name: "Forsyningskabler",
                subCategories: [],
                url: "/api/content/1088/category/126447",
              },
              {
                id: "126637",
                name: "Brandsikre kabler og gennemføringer",
                subCategories: [],
                url: "/api/content/1088/category/126637",
              },
              {
                id: "126638",
                name: "Multi / CTS-kabler",
                subCategories: [],
                url: "/api/content/1088/category/126638",
              },
              {
                id: "126656",
                name: "Styre- og motorkabler",
                subCategories: [],
                url: "/api/content/1088/category/126656",
              },
              {
                id: "126665",
                name: "Gummikabler",
                subCategories: [],
                url: "/api/content/1088/category/126665",
              },
              {
                id: "126666",
                name: "Alarm, bus og signalkabler",
                subCategories: [],
                url: "/api/content/1088/category/126666",
              },
              {
                id: "126703",
                name: "Downlight kabler",
                subCategories: [],
                url: "/api/content/1088/category/126703",
              },
              {
                id: "126722",
                name: "Installations- og monteringsledninger",
                subCategories: [],
                url: "/api/content/1088/category/126722",
              },
              {
                id: "126784",
                name: "Varmebestandige kabler og ledninger",
                subCategories: [],
                url: "/api/content/1088/category/126784",
              },
              {
                id: "100073",
                name: "Gulvvarme og frostsikring",
                subCategories: [],
                url: "/api/content/1088/category/100073",
              },
              {
                id: "127091",
                name: "Audio- og coaxialkabler",
                subCategories: [],
                url: "/api/content/1088/category/127091",
              },
              {
                id: "127092",
                name: "Auto, tændings- og ladekabler",
                subCategories: [],
                url: "/api/content/1088/category/127092",
              },
              {
                id: "101701",
                name: "Forlængerkabler",
                subCategories: [],
                url: "/api/content/1088/category/101701",
              },
              {
                id: "105830",
                name: "Kabler og stik til installationssystemer",
                subCategories: [],
                url: "/api/content/1088/category/105830",
              },
              {
                id: "100093",
                name: "Afdækning, advarsel og opmærkning",
                subCategories: [],
                url: "/api/content/1088/category/100093",
              },
              {
                id: "110497",
                name: "Kabelafrullere",
                subCategories: [],
                url: "/api/content/1088/category/110497",
              },
            ],
            url: "/api/content/1088/category/23",
          },
          {
            id: "40",
            name: "Belysning",
            subCategories: [
              {
                id: "126016",
                name: "Interaktiv & Trådløs",
                subCategories: [],
                url: "/api/content/1088/category/126016",
              },
              {
                id: "119691",
                name: "Nedhængt",
                subCategories: [],
                url: "/api/content/1088/category/119691",
              },
              {
                id: "119710",
                name: "Påbyg",
                subCategories: [],
                url: "/api/content/1088/category/119710",
              },
              {
                id: "119711",
                name: "Indbyg",
                subCategories: [],
                url: "/api/content/1088/category/119711",
              },
              {
                id: "119712",
                name: "Grund-, Spejl- & Underskabsarmatur",
                subCategories: [],
                url: "/api/content/1088/category/119712",
              },
              {
                id: "119730",
                name: "Downlights & Spot",
                subCategories: [],
                url: "/api/content/1088/category/119730",
              },
              {
                id: "119767",
                name: "Væg & Loft",
                subCategories: [],
                url: "/api/content/1088/category/119767",
              },
              {
                id: "119769",
                name: "Home Lighting",
                subCategories: [],
                url: "/api/content/1088/category/119769",
              },
              {
                id: "119785",
                name: "Industri & Sport",
                subCategories: [],
                url: "/api/content/1088/category/119785",
              },
              {
                id: "119803",
                name: "Udendørs",
                subCategories: [],
                url: "/api/content/1088/category/119803",
              },
              {
                id: "119857",
                name: "Nød & Panik",
                subCategories: [],
                url: "/api/content/1088/category/119857",
              },
              {
                id: "119872",
                name: "Arbejdslys med kabel",
                subCategories: [],
                url: "/api/content/1088/category/119872",
              },
              {
                id: "119887",
                name: "Tilbehør (Ophæng, fatninger, mv.)",
                subCategories: [],
                url: "/api/content/1088/category/119887",
              },
              {
                id: "119896",
                name: "Lysdæmper & Styring",
                subCategories: [],
                url: "/api/content/1088/category/119896",
              },
              {
                id: "119905",
                name: "Drivere, Spoler & Transformere",
                subCategories: [],
                url: "/api/content/1088/category/119905",
              },
              {
                id: "119919",
                name: "Lyskilder",
                subCategories: [],
                url: "/api/content/1088/category/119919",
              },
              {
                id: "119992",
                name: "LED Bånd, Profiler & Styring",
                subCategories: [],
                url: "/api/content/1088/category/119992",
              },
            ],
            url: "/api/content/1088/category/40",
          },
        ],
        url: "/api/content/1088/category/el",
      },
      {
        id: "staal",
        name: "Stål",
        subCategories: [
          {
            id: "3",
            name: "Stål, rustfri stål, aluminium og metaller",
            subCategories: [
              {
                id: "99950",
                name: "Rustfrit stål",
                subCategories: [],
                url: "/api/content/1088/category/99950",
              },
              {
                id: "99823",
                name: "Aluminium",
                subCategories: [],
                url: "/api/content/1088/category/99823",
              },
              {
                id: "99855",
                name: "Messing",
                subCategories: [],
                url: "/api/content/1088/category/99855",
              },
              {
                id: "99845",
                name: "Kobber",
                subCategories: [],
                url: "/api/content/1088/category/99845",
              },
              {
                id: "99869",
                name: "Stang- og båndstål",
                subCategories: [],
                url: "/api/content/1088/category/99869",
              },
              {
                id: "99900",
                name: "Armeringsstål",
                subCategories: [],
                url: "/api/content/1088/category/99900",
              },
              {
                id: "99909",
                name: "Stålbjælker",
                subCategories: [],
                url: "/api/content/1088/category/99909",
              },
              {
                id: "99920",
                name: "Stålplader",
                subCategories: [],
                url: "/api/content/1088/category/99920",
              },
              {
                id: "99930",
                name: "Blankt stål",
                subCategories: [],
                url: "/api/content/1088/category/99930",
              },
              {
                id: "99937",
                name: "Stålrør- og profiler",
                subCategories: [],
                url: "/api/content/1088/category/99937",
              },
              {
                id: "99945",
                name: "Specialstål",
                subCategories: [],
                url: "/api/content/1088/category/99945",
              },
              {
                id: "102263",
                name: "Diverse stål og metaller",
                subCategories: [],
                url: "/api/content/1088/category/102263",
              },
            ],
            url: "/api/content/1088/category/3",
          },
          {
            id: "18",
            name: "Svejsning",
            subCategories: [
              {
                id: "129900",
                name: "Böhler Maskiner, svejsebrænder og sliddele",
                subCategories: [],
                url: "/api/content/1088/category/129900",
              },
              {
                id: "129911",
                name: "Migatronic Maskiner, svejsebrænder og sliddele",
                subCategories: [],
                url: "/api/content/1088/category/129911",
              },
              {
                id: "129916",
                name: "Svejsebrænder/Kabler Binzel og Kemppi",
                subCategories: [],
                url: "/api/content/1088/category/129916",
              },
              {
                id: "111391",
                name: "Svejsemaskiner",
                subCategories: [],
                url: "/api/content/1088/category/111391",
              },
              {
                id: "111449",
                name: "Plasmaskæring",
                subCategories: [],
                url: "/api/content/1088/category/111449",
              },
              {
                id: "111976",
                name: "Ilt/Gassvejsning og flammeskæring",
                subCategories: [],
                url: "/api/content/1088/category/111976",
              },
              {
                id: "101445",
                name: "Reduktionsventiler",
                subCategories: [],
                url: "/api/content/1088/category/101445",
              },
              {
                id: "111495",
                name: "Svejseslanger/Kabler",
                subCategories: [],
                url: "/api/content/1088/category/111495",
              },
              {
                id: "111496",
                name: "Slid & reservedele TIG/MIG",
                subCategories: [],
                url: "/api/content/1088/category/111496",
              },
              {
                id: "111442",
                name: "Tilsatsmaterialer",
                subCategories: [],
                url: "/api/content/1088/category/111442",
              },
              {
                id: "101489",
                name: "Wolframslibere og elektroder",
                subCategories: [],
                url: "/api/content/1088/category/101489",
              },
              {
                id: "101426",
                name: "Beskyttelse og arbejdspladsindretning",
                subCategories: [],
                url: "/api/content/1088/category/101426",
              },
              {
                id: "112044",
                name: "Svejsetilbehør",
                subCategories: [],
                url: "/api/content/1088/category/112044",
              },
              {
                id: "101449",
                name: "Bejdseudstyr",
                subCategories: [],
                url: "/api/content/1088/category/101449",
              },
              {
                id: "112037",
                name: "Svejsekataloger/brochurer",
                subCategories: [],
                url: "/api/content/1088/category/112037",
              },
            ],
            url: "/api/content/1088/category/18",
          },
        ],
        url: "/api/content/1088/category/staal",
      },
      {
        id: "24",
        name: "Energi og klima",
        subCategories: [
          {
            id: "127769",
            name: "Solceller",
            subCategories: [],
            url: "/api/content/1088/category/127769",
          },
          {
            id: "112806",
            name: "Diverse solcelle",
            subCategories: [],
            url: "/api/content/1088/category/112806",
          },
          {
            id: "115987",
            name: "Solvarme",
            subCategories: [],
            url: "/api/content/1088/category/115987",
          },
          {
            id: "101627",
            name: "Varmepumper",
            subCategories: [],
            url: "/api/content/1088/category/101627",
          },
          {
            id: "101632",
            name: "Ventilation",
            subCategories: [],
            url: "/api/content/1088/category/101632",
          },
        ],
        url: "/api/content/1088/category/24",
      },
      {
        id: "vaerktoej",
        name: "Værktøj",
        subCategories: [
          {
            id: "12",
            name: "Værktøj og maskiner",
            subCategories: [
              {
                id: "101300",
                name: "Instrumenter",
                subCategories: [],
                url: "/api/content/1088/category/101300",
              },
              {
                id: "109622",
                name: "Akku værktøj",
                subCategories: [],
                url: "/api/content/1088/category/109622",
              },
              {
                id: "100995",
                name: "El-værktøj",
                subCategories: [],
                url: "/api/content/1088/category/100995",
              },
              {
                id: "113331",
                name: "Tilbehør til el-værktøj",
                subCategories: [],
                url: "/api/content/1088/category/113331",
              },
              {
                id: "127547",
                name: "Skærende værktøjer",
                subCategories: [],
                url: "/api/content/1088/category/127547",
              },
              {
                id: "100810",
                name: "Rengøringsmaskiner",
                subCategories: [],
                url: "/api/content/1088/category/100810",
              },
              {
                id: "101034",
                name: "Håndværktøj",
                subCategories: [],
                url: "/api/content/1088/category/101034",
              },
              {
                id: "104397",
                name: "Slibende værktøjer",
                subCategories: [],
                url: "/api/content/1088/category/104397",
              },
              {
                id: "101492",
                name: "Trykluftværktøj",
                subCategories: [],
                url: "/api/content/1088/category/101492",
              },
              {
                id: "101235",
                name: "Måleværktøj",
                subCategories: [],
                url: "/api/content/1088/category/101235",
              },
              {
                id: "111423",
                name: "Værktøj til El-arbejde",
                subCategories: [],
                url: "/api/content/1088/category/111423",
              },
              {
                id: "111424",
                name: "Værktøj til VVS-arbejde",
                subCategories: [],
                url: "/api/content/1088/category/111424",
              },
              {
                id: "101409",
                name: "Lodning, el og gas",
                subCategories: [],
                url: "/api/content/1088/category/101409",
              },
              {
                id: "114506",
                name: "Arbejdslamper og Lygter",
                subCategories: [],
                url: "/api/content/1088/category/114506",
              },
              {
                id: "102024",
                name: "Kabeltromler",
                subCategories: [],
                url: "/api/content/1088/category/102024",
              },
              {
                id: "101302",
                name: "Opmærkningsværktøj",
                subCategories: [],
                url: "/api/content/1088/category/101302",
              },
              {
                id: "101299",
                name: "Vægte",
                subCategories: [],
                url: "/api/content/1088/category/101299",
              },
              {
                id: "111453",
                name: "Maskiner",
                subCategories: [],
                url: "/api/content/1088/category/111453",
              },
            ],
            url: "/api/content/1088/category/12",
          },
          {
            id: "35",
            name: "Mekanik og teknik",
            subCategories: [
              {
                id: "129213",
                name: "Gummiplade, lister og profiler",
                subCategories: [],
                url: "/api/content/1088/category/129213",
              },
              {
                id: "129214",
                name: "Teknisk plast, plader og stænger m.m.",
                subCategories: [],
                url: "/api/content/1088/category/129214",
              },
              {
                id: "129218",
                name: "Lineær teknik",
                subCategories: [],
                url: "/api/content/1088/category/129218",
              },
              {
                id: "115320",
                name: "Pneumatik og vacuumteknik",
                subCategories: [],
                url: "/api/content/1088/category/115320",
              },
              {
                id: "124724",
                name: "INFINITY LINE - Trykluft rørsystem",
                subCategories: [],
                url: "/api/content/1088/category/124724",
              },
              {
                id: "100949",
                name: "Hydraulik",
                subCategories: [],
                url: "/api/content/1088/category/100949",
              },
              {
                id: "125430",
                name: "Transmission",
                subCategories: [],
                url: "/api/content/1088/category/125430",
              },
              {
                id: "125432",
                name: "Lejer & tilbehør",
                subCategories: [],
                url: "/api/content/1088/category/125432",
              },
              {
                id: "107118",
                name: "Pakning",
                subCategories: [],
                url: "/api/content/1088/category/107118",
              },
              {
                id: "112082",
                name: "Slanger, koblinger, fittings og tilbehør",
                subCategories: [],
                url: "/api/content/1088/category/112082",
              },
              {
                id: "125434",
                name: "Konstruktionselementer, maskinsko, greb, hjul m.m.",
                subCategories: [],
                url: "/api/content/1088/category/125434",
              },
              {
                id: "125444",
                name: "Gear og motorer",
                subCategories: [],
                url: "/api/content/1088/category/125444",
              },
              {
                id: "100253",
                name: "Servo og motion",
                subCategories: [],
                url: "/api/content/1088/category/100253",
              },
              {
                id: "126151",
                name: "Robotter",
                subCategories: [],
                url: "/api/content/1088/category/126151",
              },
            ],
            url: "/api/content/1088/category/35",
          },
          {
            id: "38",
            name: "Procesteknik",
            subCategories: [
              {
                id: "129381",
                name: "Viserinstrumenter",
                subCategories: [],
                url: "/api/content/1088/category/129381",
              },
              {
                id: "129382",
                name: "Køleautomatik",
                subCategories: [],
                url: "/api/content/1088/category/129382",
              },
              {
                id: "129383",
                name: "Regulering",
                subCategories: [],
                url: "/api/content/1088/category/129383",
              },
              {
                id: "129384",
                name: "Kalibrering",
                subCategories: [],
                url: "/api/content/1088/category/129384",
              },
              {
                id: "129385",
                name: "Proces netværk",
                subCategories: [],
                url: "/api/content/1088/category/129385",
              },
              {
                id: "129386",
                name: "Signalkonvertering",
                subCategories: [],
                url: "/api/content/1088/category/129386",
              },
              {
                id: "129387",
                name: "Industrielle pumper",
                subCategories: [],
                url: "/api/content/1088/category/129387",
              },
              {
                id: "129388",
                name: "Industrielle ventiler",
                subCategories: [],
                url: "/api/content/1088/category/129388",
              },
              {
                id: "129389",
                name: "Omrører og mixere",
                subCategories: [],
                url: "/api/content/1088/category/129389",
              },
              {
                id: "129390",
                name: "Instrumenteringsfittings",
                subCategories: [],
                url: "/api/content/1088/category/129390",
              },
              {
                id: "129391",
                name: "Laboratorie og analyse udstyr",
                subCategories: [],
                url: "/api/content/1088/category/129391",
              },
              {
                id: "104260",
                name: "Flowmåling",
                subCategories: [],
                url: "/api/content/1088/category/104260",
              },
              {
                id: "116074",
                name: "Ventiler & Aktuator",
                subCategories: [],
                url: "/api/content/1088/category/116074",
              },
              {
                id: "100266",
                name: "Proces instrumentering.",
                subCategories: [],
                url: "/api/content/1088/category/100266",
              },
              {
                id: "104272",
                name: "Niveaumåling",
                subCategories: [],
                url: "/api/content/1088/category/104272",
              },
              {
                id: "104277",
                name: "Trykmåling",
                subCategories: [],
                url: "/api/content/1088/category/104277",
              },
              {
                id: "117321",
                name: "Sensorer vand og kemi",
                subCategories: [],
                url: "/api/content/1088/category/117321",
              },
              {
                id: "118665",
                name: "Festo proces automation",
                subCategories: [],
                url: "/api/content/1088/category/118665",
              },
              {
                id: "104287",
                name: "Temperaturmåling",
                subCategories: [],
                url: "/api/content/1088/category/104287",
              },
              {
                id: "104288",
                name: "Vejeteknik",
                subCategories: [],
                url: "/api/content/1088/category/104288",
              },
              {
                id: "118047",
                name: "Frekvensomformer",
                subCategories: [],
                url: "/api/content/1088/category/118047",
              },
            ],
            url: "/api/content/1088/category/38",
          },
        ],
        url: "/api/content/1088/category/vaerktoej",
      },
    ],
    servicesData: ["Service", "Rådgivning"],
    loggedInData: [
      { page: "Indbakke", iconName: "Brev" },
      { page: "Godkend", iconName: "Kurv" },
      { page: "Ordre", iconName: "Download" },
      { page: "Returnering", iconName: "LinkPil" },
      { page: "Favoritlister", iconName: "Favorit" },
      { page: "Data", iconName: "Download" },
      { page: "Fordele", iconName: "Filtre" },
      { page: "Statestik", iconName: "Home" },
      { page: "Konti", iconName: "Indstillinger" },
      { page: "Admin", iconName: "Brugernavn" },
    ],
    footerMobileData: [
      "Kundeservice",
      "Kontakt afdelinger",
      "Om Lemvigh-Müller",
    ],
  },
  footer: {
    primaryImage: {
      name: "Footer",
      key: "19b23c09-134e-4fe3-80c3-deebeb221556",
      url: "/media/b24legko/footer.jpg",
    },
    links: [
      {
        header: "Kundeservice",
        links: [
          {
            name: "Find butik",
            type: 2,
            target: "_blank",
            url: "https://www.google.com",
          },
          {
            name: "FAQ",
            type: 0,
            url: "/radgivning/",
          },
          {
            name: "Handelsbetingelser",
            type: 2,
            target: "_blank",
            url: "https://www.google.dk",
          },
          {
            name: "Returnering",
            type: 0,
            url: "/",
          },
          {
            name: "Reklamation",
            type: 0,
            target: "_blank",
            url: "/service/",
          },
          {
            name: "Salgs & leveringsbetingelser",
            type: 0,
            url: "/service/",
          },
          {
            name: "Levering i helligdage",
            type: 0,
            url: "/service/",
          },
          {
            name: "Cookies",
            type: 0,
            target: "_blank",
            url: "/service/",
          },
        ],
      },
      {
        header: "Kontakt",
        links: [
          {
            name: "Kontakt LMe-support",
            type: 0,
            url: "/",
          },
          {
            name: "Kontakt EDI support",
            type: 0,
            url: "/service/",
          },
          {
            name: "Kontakt PIM Stamdata",
            type: 0,
            target: "_blank",
            url: "/service/",
          },
          {
            name: "Kontaktformular",
            type: 0,
            url: "/service/",
          },
          {
            name: "Kontaktformular for leverandører",
            type: 0,
            url: "/service/",
          },
          {
            name: "Teknisk suppport",
            type: 0,
            target: "_blank",
            url: "/service/",
          },
          {
            name: "Kundeservice",
            type: 0,
            url: "/information/",
          },
          {
            name: "Hotline",
            type: 0,
            url: "/radgivning/",
          },
        ],
      },
      {
        header: "Om Lemvigh-Müller",
        links: [
          {
            name: "Om Lemvigh-Müller",
            type: 2,
            target: "_blank",
            url: "https://www.lemu.dk/",
          },
          {
            name: "Nyheder og Presse",
            type: 0,
            url: "/radgivning/",
          },
          {
            name: "Organisation og profil",
            type: 0,
            url: "/radgivning/",
          },
          {
            name: "Job & karriere",
            type: 0,
            target: "_blank",
            url: "/service/",
          },
          {
            name: "Bliv elev",
            type: 0,
            url: "/radgivning/",
          },
          {
            name: "For leverandører",
            type: 0,
            url: "/service/",
          },
          {
            name: "Kontrolrapport fødevarestyrelsen",
            type: 0,
            url: "/om-os/",
          },
          {
            name: "Beskyttelse af persondata",
            type: 2,
            target: "_blank",
            url: "https://google.dk",
          },
        ],
      },
    ],
    bottomLinks: {
      header: "Følg os på",
      links: [
        {
          name: "LinkedIn",
          type: 2,
          target: "_blank",
          url: "https://www.linkedin.com/company/lemvigh-m-ller-a-s",
        },
        {
          name: "Facebook",
          type: 2,
          target: "_blank",
          url: "https://www.facebook.com/lemvighmuller/",
        },
        {
          name: "Youtube",
          type: 2,
          target: "_blank",
          url: "http://www.youtube.com/user/LemuTV",
        },
      ],
    },
    bottomText: "© 2021 Lemvigh-Müller - Alle rettigheder forbeholdes",
  },
};

module.exports.lmCategoryData = {
  categories: [
    {
      category: "Opmaerkning",
      url: "/opmaerkning/",
      imageUrl:
        "https://assets.cdnlemu.dk/api/sitecore/asset/get?id=043d-80c3-43e8-8f20-65eea1aefca0&size=DrillDownCatalogThumbnail",
      links: [
        {
          name: "Rittal Spelsberg Hager",
          type: 0,
          url: "/Rittal Spelsberg Hager/",
        },
        {
          name: "Indsats",
          type: 0,
          url: "/Indsats/",
        },
        {
          name: "Rammer",
          type: 0,
          url: "/Rammer/",
        },
      ],
    },
    {
      category: "Faerdigmonterede gruppetavler",
      url: "/faerdigmonterede-gruppetavler/",
      imageUrl:
        "https://assets.cdnlemu.dk/api/sitecore/asset/get?id=e19f-0bc8-479f-8c01-7f44fb6f6394&size=DrillDownCatalogThumbnail",
      links: [
        {
          name: "Hager boligtavler ( Hager afdækning )",
          type: 0,
          url: "/Hager boligtavler ( Hager afdækning )/",
        },
        {
          name: "Unite boligtavler ( LK afdækning )",
          type: 0,
          url: "/Unite boligtavler ( LK afdækning )/",
        },
      ],
    },
    {
      category: "Tavlefrontstik",
      url: "/tavlefrontstik/",
      imageUrl:
        "https://assets.cdnlemu.dk/api/sitecore/asset/get?id=42e0-f804-44d7-9aca-8f3adcb6ec87&size=DrillDownCatalogThumbnail",
      links: [
        {
          name: "PVC rør",
          type: 0,
          url: "/pvc-ror/",
        },
      ],
    },
    {
      category: "Kasse-modulsystem",
      url: "/kasse-modulsystem/",
      imageUrl:
        "https://assets.cdnlemu.dk/api/sitecore/asset/get?id=6c8f-7b9f-4e4a-bc6f-c0b613d69cf2&size=DrillDownCatalogThumbnail",
      links: [],
    },
  ],
};
